[package]
name = "nyoka"
version = "0.1.0"
edition = "2021"
authors = ["Isaka-James <mr.isakajames@gmail.com"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "*"
piston_window = "*"
